<a href="https://colab.research.google.com/github/chandana-daggupati/CHANDANA/blob/main/20116_FDS__Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Q1
sets={"aman","222",11,22}
t = tuple(sets)
print(t)

(11, 'aman', '222', 22)


In [6]:
#Q2
dict = {"Rollno":"CB.EN.U4CSE20116", "First Name": "Chandana", "Last Name": "Daggupati", "DOB": "10/01/2003"}
print(dict)
x = dict.values()
print(x)
y = dict.keys()
print(y)

{'Rollno': 'CB.EN.U4CSE20116', 'First Name': 'Chandana', 'Last Name': 'Daggupati', 'DOB': '10/01/2003'}
dict_values(['CB.EN.U4CSE20116', 'Chandana', 'Daggupati', '10/01/2003'])
dict_keys(['Rollno', 'First Name', 'Last Name', 'DOB'])


In [7]:
#Q3
import numpy as np
np.random.seed(2)
r = np.random.rand(4,6)
print(r)

[[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467 0.26682728 0.62113383 0.52914209]
 [0.13457995 0.51357812 0.18443987 0.78533515 0.85397529 0.49423684]
 [0.84656149 0.07964548 0.50524609 0.0652865  0.42812233 0.09653092]]


In [9]:
#Q4
import random
n = random.uniform(0.0,1.0)
print(n)
print(abs(-1234))

0.11133479544059399
1234


In [12]:
#Q5
n = random.randint(20,90)
print(n)

47


In [13]:
#Q6
list1 = [11,12,13,14,15]
print(random.sample(list1, 3))
random.shuffle(list1)
print(list1)
print(np.random.choice(list1,1))

[11, 15, 14]
[14, 11, 12, 13, 15]
[14]


In [14]:
#Q7
myfile = open("King.txt","w")
str1 = "The King is Dead, Long Live The King"
myfile.write(str1)
myfile.close()
myfile = open("King.txt","r")
print(myfile.read())
myfile.close()

The King is Dead, Long Live The King


In [23]:
#Q8
def my_function():
  #if_else
  min_age = 18
  your_age = 19
  if your_age>min_age:
    print("You are above 18!!")
    print("You are eligible to vote :)")
  else:
    print("You are under 18!!!")
    print("You are not eligible to vote :(")
  print("----------------------------------------------------------------")
  #if_elif
  a = 33
  b = 33
  if b>a:
    print("b is greater than a")
  elif a==b:
    print("a and b are equal")
  print("-----------------------------------------------------------------")
  #while
  i = 1
  while i<6:
    print(i)
    i += 1
  print("------------------------------------------------------------------")
  #for loop
  for x in "apple":
    print(x)
  print("-------------------------------------------------------------------")
  
   #break_statement
  i=1
  while i<6:
     print(i)
     if i==3:
       break
     i += 1
  print("--------------------------------------------------------------------")
    #continue_statement
  i = 0
  while i<6:
    i += 1
    if i==3:
      continue
    print(i)


  

  

my_function()


You are above 18!!
You are eligible to vote :)
----------------------------------------------------------------
a and b are equal
-----------------------------------------------------------------
1
2
3
4
5
------------------------------------------------------------------
a
p
p
l
e
-------------------------------------------------------------------
1
2
3
--------------------------------------------------------------------
1
2
4
5
6


In [24]:
#Q9
str = "The King is Dead, Long Live The King"
print(str)
print(str[0])
print(str[2:6])
print(str[2:])
print(str.split())

The King is Dead, Long Live The King
T
e Ki
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [25]:
#Q10
arr = np.array([1,4,5,8])
print(arr[0:1],arr[1:2])

[1] [4]


In [26]:
#Q11
arr = [[1,2,3],[4,5,6]]
print(arr)

[[1, 2, 3], [4, 5, 6]]


In [27]:
#Q12
arr = [[1,2,3],[4,5,6]]
print(arr)
print(arr[1:])
for i in arr:
  print(i[1:])
print(len(arr))

[[1, 2, 3], [4, 5, 6]]
[[4, 5, 6]]
[2, 3]
[5, 6]
2


In [28]:
#Q13
x=np.array([1,2,3,4,5,6,7,8,9,10])
x.shape=(2,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
#Q14
list =[1,2,3]
x=np.array(list)
print(x)

[1 2 3]


In [30]:
#Q15
arr = np.array([1,2,3])
arr.fill(9)
print(arr)

[9 9 9]


In [31]:
#Q16
arr = np.array([2,4,5])
print("Sum of all elements in array:")
print(np.sum(arr))

Sum of all elements in array:
11


In [32]:
#Q17
arr = np.array([2,4,5])
print("Product of all the elements in array:")
print(np.prod(arr))


Product of all the elements in array:
40


In [33]:
#Q18
arr = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(arr),np.var(arr),np.amax(arr),np.amin(arr),np.argmin(arr),np.argmax(arr),np.median(arr),np.std(arr))

12.461538461538462 367.32544378698225 56 1 1 12 2.0 19.165736192147232


In [34]:
#Q19
arr = np.array([1,1,4,5,5,5,7])
print(np.unique(arr))

[1 4 5 7]


In [35]:
#Q20
arr1 = np.array([1,2,3])
arr2 = np.array([0,1,1])
print(np.dot(arr1,arr2))


5


In [38]:
#Q21
mat = np.array([[2,2,4],
               [1,3,5],
               [2,3,4]])
evalues, evectors = np.linalg.eig(mat)
print("Eigen Values: ", evalues)
print("Eigen Vectors: ", evectors)

Eigen Values:  [ 8.80916362  0.92620912 -0.73537273]
Eigen Vectors:  [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [39]:
#Q22
x_sim = np.array([11,22,11,31])
y_sim = np.array([25,33,31,28])
my_rho = np.corrcoef(x_sim, y_sim)

print(my_rho)

[[1.         0.15997968]
 [0.15997968 1.        ]]
